# Generated by Django 4.0.6 on 2022-08-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall_lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField()),
                ('id_lecture_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_lecture.hall')),
            ],
            options={
                'unique_together': {('booked_date', 'id_lecture_hall')},
            },
        ),
    ]
