# Generated by Django 4.0.6 on 2022-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_lecture', '0002_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
